name: Build and Push Docker Image

on:
  push:
    branches: [ main, staging ]

env:
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
  GAR_REPOSITORY: ${{ secrets.GAR_REPOSITORY }}
  IMAGE_NAME: super-mario-rl

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set env variables
      run: |
        echo "Branch: ${{ github.ref }}"
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          echo "PROJECT_ID=${{ secrets.PROJECT_ID_PROD }}" >> $GITHUB_ENV
          echo "WIF_PROVIDER=${{ secrets.WIF_PROVIDER_PROD }}" >> $GITHUB_ENV
          echo "WIF_SERVICE_ACCOUNT=${{ secrets.WIF_SERVICE_ACCOUNT_PROD }}" >> $GITHUB_ENV
          echo "DEBUG: Using prod secrets"
          echo "DEBUG: PROJECT_ID=${{ secrets.PROJECT_ID_PROD }}"
          echo "DEBUG: WIF_PROVIDER=${{ secrets.WIF_PROVIDER_PROD }}"
          echo "DEBUG: WIF_SERVICE_ACCOUNT=${{ secrets.WIF_SERVICE_ACCOUNT_PROD }}"
        elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
          echo "ENVIRONMENT=nonprod" >> $GITHUB_ENV
          echo "PROJECT_ID=${{ secrets.PROJECT_ID_NONPROD }}" >> $GITHUB_ENV
          echo "WIF_PROVIDER=${{ secrets.WIF_PROVIDER_NONPROD }}" >> $GITHUB_ENV
          echo "WIF_SERVICE_ACCOUNT=${{ secrets.WIF_SERVICE_ACCOUNT_NONPROD }}" >> $GITHUB_ENV
          echo "DEBUG: Using nonprod secrets"
          echo "DEBUG: PROJECT_ID=${{ secrets.PROJECT_ID_NONPROD }}"
          echo "DEBUG: WIF_PROVIDER=${{ secrets.WIF_PROVIDER_NONPROD }}"
          echo "DEBUG: WIF_SERVICE_ACCOUNT=${{ secrets.WIF_SERVICE_ACCOUNT_NONPROD }}"
        fi
        echo "IMAGE_TAG=latest" >> $GITHUB_ENV

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        workload_identity_provider: ${{ env.WIF_PROVIDER }}
        service_account: ${{ env.WIF_SERVICE_ACCOUNT }}
    
    - name: Debug auth configuration
      run: |
        echo "DEBUG: Final env vars being used:"
        echo "PROJECT_ID: ${{ env.PROJECT_ID }}"
        echo "WIF_PROVIDER: ${{ env.WIF_PROVIDER }}"
        echo "WIF_SERVICE_ACCOUNT: ${{ env.WIF_SERVICE_ACCOUNT }}"
        echo "GAR_LOCATION: ${{ env.GAR_LOCATION }}"
        echo "GAR_REPOSITORY: ${{ env.GAR_REPOSITORY }}"

    - name: Configure Docker to use gcloud
      run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        IMAGE_URL="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}"
        IMAGE_URL="${IMAGE_URL}:${{ env.IMAGE_TAG }}"

        echo "Building image..."
        docker build -t $IMAGE_URL .

        echo "Pushing to artifact registry..."
        docker push $IMAGE_URL 
