name: Build and Push Docker Image

on:
  push:
    branches: [ main, staging ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
  GAR_REPOSITORY: ${{ secrets.GAR_REPOSITORY }}
  IMAGE_NAME: super-mario-rl

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set env variables
      run: |
        echo "Branch: ${{ github.ref }}"
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          echo "ENVIRONMENT=prod" >> $GITHUB_ENV
        elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
          echo "ENVIRONMENT=nonprod" >> $GITHUB_ENV
        fi
        echo "IMAGE_TAG=latest" >> $GITHUB_ENV

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

    - name: Configure Docker to use gcloud
      run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        IMAGE_URL="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}"
        IMAGE_URL="${IMAGE_URL}:${{ env.IMAGE_TAG }}"

        echo "Building image..."
        docker build -t $IMAGE_URL .

        echo "Pushing to artifact registry..."
        docker push $IMAGE_URL 

